// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: change_application_status.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Statuses int32

const (
	Statuses_INSTALL   Statuses = 0
	Statuses_UNINSTALL Statuses = 1
	Statuses_UPDATED   Statuses = 2
)

// Enum value maps for Statuses.
var (
	Statuses_name = map[int32]string{
		0: "INSTALL",
		1: "UNINSTALL",
		2: "UPDATED",
	}
	Statuses_value = map[string]int32{
		"INSTALL":   0,
		"UNINSTALL": 1,
		"UPDATED":   2,
	}
)

func (x Statuses) Enum() *Statuses {
	p := new(Statuses)
	*p = x
	return p
}

func (x Statuses) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Statuses) Descriptor() protoreflect.EnumDescriptor {
	return file_change_application_status_proto_enumTypes[0].Descriptor()
}

func (Statuses) Type() protoreflect.EnumType {
	return &file_change_application_status_proto_enumTypes[0]
}

func (x Statuses) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Statuses.Descriptor instead.
func (Statuses) EnumDescriptor() ([]byte, []int) {
	return file_change_application_status_proto_rawDescGZIP(), []int{0}
}

type ChangeApplicationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionUUID  string   `protobuf:"bytes,1,opt,name=VersionUUID,proto3" json:"VersionUUID,omitempty"`
	EnterpriseID string   `protobuf:"bytes,2,opt,name=EnterpriseID,proto3" json:"EnterpriseID,omitempty"`
	Status       Statuses `protobuf:"varint,3,opt,name=Status,proto3,enum=Statuses" json:"Status,omitempty"`
}

func (x *ChangeApplicationStatusRequest) Reset() {
	*x = ChangeApplicationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_change_application_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeApplicationStatusRequest) ProtoMessage() {}

func (x *ChangeApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_change_application_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_change_application_status_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeApplicationStatusRequest) GetVersionUUID() string {
	if x != nil {
		return x.VersionUUID
	}
	return ""
}

func (x *ChangeApplicationStatusRequest) GetEnterpriseID() string {
	if x != nil {
		return x.EnterpriseID
	}
	return ""
}

func (x *ChangeApplicationStatusRequest) GetStatus() Statuses {
	if x != nil {
		return x.Status
	}
	return Statuses_INSTALL
}

var File_change_application_status_proto protoreflect.FileDescriptor

var file_change_application_status_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x89, 0x01, 0x0a, 0x1e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x55, 0x55, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70,
	0x72, 0x69, 0x73, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x49, 0x44, 0x12, 0x21, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x65, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x33, 0x0a,
	0x08, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x53,
	0x54, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x49, 0x4e, 0x53, 0x54,
	0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44,
	0x10, 0x02, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_change_application_status_proto_rawDescOnce sync.Once
	file_change_application_status_proto_rawDescData = file_change_application_status_proto_rawDesc
)

func file_change_application_status_proto_rawDescGZIP() []byte {
	file_change_application_status_proto_rawDescOnce.Do(func() {
		file_change_application_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_change_application_status_proto_rawDescData)
	})
	return file_change_application_status_proto_rawDescData
}

var file_change_application_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_change_application_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_change_application_status_proto_goTypes = []interface{}{
	(Statuses)(0),                          // 0: Statuses
	(*ChangeApplicationStatusRequest)(nil), // 1: ChangeApplicationStatusRequest
}
var file_change_application_status_proto_depIdxs = []int32{
	0, // 0: ChangeApplicationStatusRequest.Status:type_name -> Statuses
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_change_application_status_proto_init() }
func file_change_application_status_proto_init() {
	if File_change_application_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_change_application_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeApplicationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_change_application_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_change_application_status_proto_goTypes,
		DependencyIndexes: file_change_application_status_proto_depIdxs,
		EnumInfos:         file_change_application_status_proto_enumTypes,
		MessageInfos:      file_change_application_status_proto_msgTypes,
	}.Build()
	File_change_application_status_proto = out.File
	file_change_application_status_proto_rawDesc = nil
	file_change_application_status_proto_goTypes = nil
	file_change_application_status_proto_depIdxs = nil
}
